progname = 'Flame';

IncludePath = ['../../src/','../../src/include']
LibsPath = ['../../']   
Libs = ['Distillate','SDL','SDL_mixer', 'SDL_image']

CommonFlags = ' -Wall -pedantic'

debug    = ARGUMENTS.get('debug', 0)
shared   = ARGUMENTS.get('shared', 0)
render   = ARGUMENTS.get('render', 'sdl')

progenv = Environment( CPPFLAGS = CommonFlags)
progenv.VariantDir('build/', 'src/')

if int(debug):
	progenv.Append(CPPFLAGS = ' -g -ggdb')

if render == 'sdl':
    progenv.Append(CPPDEFINES = 'SDL_RENDER')
    Libs.append('SDL_ttf')

elif render == 'gl':
    progenv.Append(CPPDEFINES = 'GL_RENDER')
    Libs.append('GL')

files = Split("""
main.cpp
FlameState.cpp
""")

progenv.Program(target = progname, source = files, CPPPATH = IncludePath, LIBS = Libs, LIBPATH = LibsPath)

